use_frameworks!

target 'ReSwiftDataSource_Example' do
  pod 'ReSwiftDataSource', :path => '../'

  target 'ReSwiftDataSource_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
