use_frameworks!

target 'ReSwiftDataSource_Example' do
  pod 'ReSwiftDataSource', :path => '../'

  target 'ReSwiftDataSource_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
